# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = Test
DESTDIR = ../x64/Debug
QT += core
CONFIG += debug console
DEFINES += _UNICODE WIN64
INCLUDEPATH += . \
    ./GeneratedFiles/$(ConfigurationName) \
    ./../include \
    ../../../McLogQt/McLogQt
LIBS += -L"$(OutDir)" \
    -L"../../../McLogQt/x64/Debug" \
    -lMcLogQtd \
    -lMcIocContainerd
DEPENDPATH += .
MOC_DIR += ./GeneratedFiles/$(ConfigurationName)
OBJECTS_DIR += debug
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
include(Test.pri)
